#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User

easy_admin:
  entities:
    Recipe:
      class: App\Entity\Recipe
      label: 'Recettes'
      list:
        title: 'Liste des recettes'
    Category:
      class: App\Entity\Category
      label: 'Catégories'
      list:
        title: "Liste des catégories"

