vich_uploader:
    db_driver: orm
    mappings:
        pictures_images:
            uri_prefix:         '%app.path.uploads_dir%'
            upload_destination: '%kernel.project_dir%/public%app.path.uploads_dir%'


